name: Python application

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Możesz zmienić wersję Pythona na potrzebną

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Zakładam, że masz plik requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover  # Odpala testy unittests
